// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBn0x8jBAmfFXXieoVyplZUnwzKM_fb5s',
    appId: '1:88906174066:web:34f3721a40536b767ebceb',
    messagingSenderId: '88906174066',
    projectId: 'test-app-1fdbc',
    authDomain: 'test-app-1fdbc.firebaseapp.com',
    storageBucket: 'test-app-1fdbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByX-a1kPKEdiUtZYK1JCWLQt8VkIlx7HM',
    appId: '1:88906174066:android:96cc026935ed71ef7ebceb',
    messagingSenderId: '88906174066',
    projectId: 'test-app-1fdbc',
    storageBucket: 'test-app-1fdbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOJNJBuEeV_kt82AkG5UPzh-2jwrUi2M',
    appId: '1:88906174066:ios:69061b25eea644017ebceb',
    messagingSenderId: '88906174066',
    projectId: 'test-app-1fdbc',
    storageBucket: 'test-app-1fdbc.appspot.com',
    iosBundleId: 'com.zeinabshop.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVOJNJBuEeV_kt82AkG5UPzh-2jwrUi2M',
    appId: '1:88906174066:ios:69061b25eea644017ebceb',
    messagingSenderId: '88906174066',
    projectId: 'test-app-1fdbc',
    storageBucket: 'test-app-1fdbc.appspot.com',
    iosBundleId: 'com.zeinabshop.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBn0x8jBAmfFXXieoVyplZUnwzKM_fb5s',
    appId: '1:88906174066:web:91a76813a7326ce07ebceb',
    messagingSenderId: '88906174066',
    projectId: 'test-app-1fdbc',
    authDomain: 'test-app-1fdbc.firebaseapp.com',
    storageBucket: 'test-app-1fdbc.appspot.com',
  );
}
